spring:
  profiles:
    active:
      - release


---

spring:
  profile : release
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: false
  datasource:
#    driver-class-name: org.h2.driver
    url: jdbc:h2:mem:usr-mstr
    username: admin
    password: admin
  jpa:
    show-sql: true
server:
  port: 9090

management:
  endpoint:
    web:
      exposure:
        include: "*"
